### ISSUE TITLE
Time for a release?

### ISSUE THREAD

**Issue by michaelweiser** [edgester/puppet-module-kerberos#26]
Hi Jason,

I'm now at a point where I'd like to package the module for Debian. A release would be very helpful for that, possiby even to PuppetForge?

Thanks!
Michael

**Comment by edgester** [comment]
Would you help to fix the issues exposed via the travis tests, specifically the 'lint' and 'spec' tests?

**Comment by edgester** [comment]
The lint problems are fixed.

**Comment by edgester** [comment]
Version 0.2.0 tagged and uploaded to puppetforge
