### ISSUE TITLE
$kprop_cron_hour tries to illegally access not yet evaluated $kprop_cron_hour

### ISSUE THREAD

**Issue by martialblog** [edgester/puppet-module-kerberos#48]
Hi,

I've encountered an error while using the Module and this might be due to this:

class kerberos::server::kprop (
  $kprop_cron_path = $kerberos::kprop_cron_path,
  **$kprop_cron_hour = $kprop_cron_hour**,

Fix provided here:
https://github.com/martialblog/puppet-module-kerberos/commit/5beb1486c5fe5d37ad7e9afcee195be5066c3e3c

Cheers,
Markus

**Comment by edgester** [comment]
Send me a pull request.
