### ISSUE TITLE
Refactor/Extend tests

### ISSUE THREAD

**Issue by martialblog** [edgester/puppet-module-kerberos#50]
Hi, 

I've updated the test a little bit and added an acceptance test. Had some issues with testing the Master installation in Travis CI, so only the client is currently tested. However it should be easy to extend the tests in the future. 

https://github.com/martialblog/puppet-module-kerberos/tree/refactor_tests

This is based on my previous Pull Request, so it's best to wait until it's merged and then I'm gonna rebase.

Feedback is welcome.
Cheers

**Comment by edgester** [comment]
The branch looks good to me.

**Comment by martialblog** [comment]
Alright, so I'm gonna try to get a running beaker test for the master this week. Otherwise I think it's better than nothing. 

https://github.com/martialblog/puppet-module-kerberos/commit/735005330ddd4a26445359c64acac52819772431

**Comment by edgester** [comment]
Merged
