### ISSUE TITLE
github missing tags to match the forge

### ISSUE THREAD

**Issue by brettswift** [edgester/puppet-module-kerberos#53]
It's a good practice to tag repos with the versions that are being released to the forge.

This is because most (I think)  r10k or code manager users source from git urls as it's a little faster than sourcing from the forge. 

Not doing it limits the uptake and usage of the module a bit.

Would you be able to put this in your process and tag the 0.3.1 release?  

I haven't used this module but with a cursory look at the code I think I will prefer this one over others. :)

**Comment by edgester** [comment]
Oops. v0.3.0 and v0.3.1 are tagged now. I've been tagging them, but I forgot to add "--tags" to my git push commands.

**Comment by brettswift** [comment]
Ah ! Ok thank you
